/* doss_get_cfg.h */

#ifndef ___DOSS__GET_CFG__H___
#define ___DOSS__GET_CFG__H___

/*
 * #define DEF_GET_DOSS_VER_VER_L
 * #define DEF_GET_DOSS_VER_VER_H
 * #define DEF_GET_DOSS_VER_COMP
 * #define DEF_GET_DOSS_DO0_FTR_RGB
 * #define DEF_GET_DOSS_DO0_FTR_LVDS
 * #define DEF_GET_DOSS_DO0_FTR_DSI
 * #define DEF_GET_DOSS_DO0_FTR_EDP
 * #define DEF_GET_DOSS_DO0_FTR_TVE
 * #define DEF_GET_DOSS_DO0_FTR_HDMI
 * #define DEF_GET_DOSS_DO0_FTR_TCON
 * #define DEF_GET_DOSS_DO1_FTR_RGB
 * #define DEF_GET_DOSS_DO1_FTR_LVDS
 * #define DEF_GET_DOSS_DO1_FTR_DSI
 * #define DEF_GET_DOSS_DO1_FTR_EDP
 * #define DEF_GET_DOSS_DO1_FTR_TVE
 * #define DEF_GET_DOSS_DO1_FTR_HDMI
 * #define DEF_GET_DOSS_DO1_FTR_TCON
 * #define DEF_GET_DOSS_RESET_RST
 * #define DEF_GET_DOSS_ROUTE_SRC_DO0
 * #define DEF_GET_DOSS_ROUTE_SRC_DO1
 * #define DEF_GET_DOSS_TCON0_CTRL_SLAVE
 * #define DEF_GET_DOSS_TCON0_CTRL_GATE
 * #define DEF_GET_DOSS_TCON0_CTRL_RST
 * #define DEF_GET_DOSS_TCON1_CTRL_SLAVE
 * #define DEF_GET_DOSS_TCON1_CTRL_GATE
 * #define DEF_GET_DOSS_TCON1_CTRL_RST
 * #define DEF_GET_DOSS_TCON0_CLK_DIV0
 * #define DEF_GET_DOSS_TCON0_CLK_DIV1
 * #define DEF_GET_DOSS_TCON0_CLK_GATE
 * #define DEF_GET_DOSS_TCON1_CLK_DIV0
 * #define DEF_GET_DOSS_TCON1_CLK_DIV1
 * #define DEF_GET_DOSS_TCON1_CLK_GATE
 * #define DEF_GET_DOSS_LVDS0_CTRL_SLAVE
 * #define DEF_GET_DOSS_LVDS0_CTRL_GATE
 * #define DEF_GET_DOSS_LVDS0_CTRL_RST
 * #define DEF_GET_DOSS_LVDS1_CTRL_SLAVE
 * #define DEF_GET_DOSS_LVDS1_CTRL_GATE
 * #define DEF_GET_DOSS_LVDS1_CTRL_RST
 * #define DEF_GET_DOSS_LVDS0_CLK_GATE
 * #define DEF_GET_DOSS_LVDS1_CLK_GATE
 * #define DEF_GET_DOSS_MIPI_DSI0_CTRL_SLAVE
 * #define DEF_GET_DOSS_MIPI_DSI0_CTRL_GATE
 * #define DEF_GET_DOSS_MIPI_DSI0_CTRL_RST
 * #define DEF_GET_DOSS_MIPI_DSI1_CTRL_SLAVE
 * #define DEF_GET_DOSS_MIPI_DSI1_CTRL_GATE
 * #define DEF_GET_DOSS_MIPI_DSI1_CTRL_RST
 * #define DEF_GET_DOSS_MIPI_DSI0_REF_CLK_DIV0
 * #define DEF_GET_DOSS_MIPI_DSI0_REF_CLK_GATE
 * #define DEF_GET_DOSS_MIPI_DSI1_REF_CLK_DIV0
 * #define DEF_GET_DOSS_MIPI_DSI1_REF_CLK_GATE
 * #define DEF_GET_DOSS_MIPI_DSI0_CFG_CLK_GATE
 * #define DEF_GET_DOSS_MIPI_DSI1_CFG_CLK_GATE
 * #define DEF_GET_DOSS_TVE0_CTRL_SLAVE
 * #define DEF_GET_DOSS_TVE0_CTRL_GATE
 * #define DEF_GET_DOSS_TVE0_CTRL_RST
 * #define DEF_GET_DOSS_TVE1_CTRL_SLAVE
 * #define DEF_GET_DOSS_TVE1_CTRL_GATE
 * #define DEF_GET_DOSS_TVE1_CTRL_RST
 * #define DEF_GET_DOSS_TVE0_CLK_DIV0
 * #define DEF_GET_DOSS_TVE0_CLK_GATE
 * #define DEF_GET_DOSS_TVE1_CLK_DIV0
 * #define DEF_GET_DOSS_TVE1_CLK_GATE
*/

#endif /* ___DOSS__GET_CFG__H___ */
