LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
ifeq ($(BOARD_WIFI_VENDOR), realtek)
LOCAL_CFLAGS += -DREALTEK_MODULE
endif
LOCAL_MODULE := libwifi_softap
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := \
	wifi_softap.c
LOCAL_C_INCLUDES :=
#LOCAL_STRIP_MODULE := false
LOCAL_CFLAGS +=
LOCAL_CPPFLAGS :=
LOCAL_LDFLAGS :=
LOCAL_STATIC_LIBRARIES :=
LOCAL_SHARED_LIBRARIES := liblog
include $(BUILD_SHARED_LIBRARY)
