##############################################################################################
## Description: Entry makefile.
## History
## Version		Date		Author		Description
## V1.0		  2019.03.28    lomboswer		Create File.
##############################################################################################

all:
	gcc -o ws_http http_main.c mongoose.c web_biz_api.c ws_http.c cJSON.c biz_api.c -I. -I/home/xiaowei/workspace/virgo/system/core/include -lpthread -lm
