PRODUCT_COPY_FILES += \
	frameworks/nn/lib/sv810/ONet_blobs_mapped.bin:rootfs/usr/share/ax/ONet_blobs_mapped.bin \
	frameworks/nn/lib/sv810/ONet_net_mapped.bin:rootfs/usr/share/ax/ONet_net_mapped.bin \
	frameworks/nn/lib/sv810/face_quality_warp_blobs_mapped.bin:rootfs/usr/share/ax/face_quality_warp_blobs_mapped.bin \
	frameworks/nn/lib/sv810/face_quality_warp_net_mapped.bin:rootfs/usr/share/ax/face_quality_warp_net_mapped.bin \
	frameworks/nn/lib/sv810/RGBAdaptedCaffeNet_blobs_mapped.bin:rootfs/usr/share/ax/RGBAdaptedCaffeNet_blobs_mapped.bin \
	frameworks/nn/lib/sv810/RGBAdaptedCaffeNet_net_mapped.bin:rootfs/usr/share/ax/RGBAdaptedCaffeNet_net_mapped.bin \
	frameworks/nn/lib/sv810/RGB_COLOR.ezb:rootfs/usr/share/ax/RGB_COLOR.ezb \
	frameworks/nn/lib/sv810/RGB_COLOR.bin:rootfs/usr/share/ax/RGB_COLOR.bin \
	frameworks/nn/lib/sv810/RGB_Liveness.ezb:rootfs/usr/share/ax/RGB_Liveness.ezb \
	frameworks/nn/lib/sv810/RGB_Liveness.bin:rootfs/usr/share/ax/RGB_Liveness.bin \
	frameworks/nn/lib/sv810/headpose.ezb:rootfs/usr/share/ax/headpose.ezb \
	frameworks/nn/lib/sv810/headpose.bin:rootfs/usr/share/ax/headpose.bin \
	frameworks/nn/lib/sv810/face_attr_blobs_mapped.bin:rootfs/usr/share/ax/face_attr_blobs_mapped.bin \
	frameworks/nn/lib/sv810/face_attr_net_mapped.bin:rootfs/usr/share/ax/face_attr_net_mapped.bin \
	frameworks/nn/lib/sv810/model_recg.ezb:rootfs/usr/share/ax/model_recg.ezb \
	frameworks/nn/lib/sv810/model_recg.bin:rootfs/usr/share/ax/model_recg.bin \
	frameworks/nn/lib/sv810/NIR_Liveness_indoors_qt.ezb:rootfs/usr/share/ax/NIR_Liveness_indoors_qt.ezb \
	frameworks/nn/lib/sv810/NIR_Liveness_indoors_qt.bin:rootfs/usr/share/ax/NIR_Liveness_indoors_qt.bin \
	frameworks/nn/lib/sv810/NIR_Liveness_indoors_qt_mask.ezb:rootfs/usr/share/ax/NIR_Liveness_indoors_qt_mask.ezb \
	frameworks/nn/lib/sv810/NIR_Liveness_indoors_qt_mask.bin:rootfs/usr/share/ax/NIR_Liveness_indoors_qt_mask.bin \
	frameworks/nn/lib/sv810/NIR_Liveness_outdoors.ezb:rootfs/usr/share/ax/NIR_Liveness_outdoors.ezb \
	frameworks/nn/lib/sv810/NIR_Liveness_outdoors.bin:rootfs/usr/share/ax/NIR_Liveness_outdoors.bin \
	frameworks/nn/lib/sv810/facedet.bin:rootfs/usr/share/ax/facedet.bin \
	frameworks/nn/lib/sv810/facedet0.ezb:rootfs/usr/share/ax/facedet0.ezb \
	frameworks/nn/lib/sv810/facedet1.ezb:rootfs/usr/share/ax/facedet1.ezb \
	frameworks/nn/lib/sv810/facedet2.ezb:rootfs/usr/share/ax/facedet2.ezb \
	frameworks/nn/lib/sv810/facedet3.ezb:rootfs/usr/share/ax/facedet3.ezb \
	frameworks/nn/lib/sv810/facedet4.ezb:rootfs/usr/share/ax/facedet4.ezb \
	frameworks/nn/lib/sv810/facedet10.ezb:rootfs/usr/share/ax/facedet10.ezb \
	frameworks/nn/lib/sv810/facedet11.ezb:rootfs/usr/share/ax/facedet11.ezb \
	frameworks/nn/lib/sv810/facedet12.ezb:rootfs/usr/share/ax/facedet12.ezb \
	frameworks/nn/lib/sv810/facedet13.ezb:rootfs/usr/share/ax/facedet13.ezb \
	frameworks/nn/lib/sv810/facedet14.ezb:rootfs/usr/share/ax/facedet14.ezb \
	frameworks/nn/lib/sv810/face_mask.bin:rootfs/usr/share/ax/face_mask.bin \
	frameworks/nn/lib/sv810/face_mask.ezb:rootfs/usr/share/ax/face_mask.ezb \
	frameworks/nn/lib/sv810/quantize_out.bin:rootfs/usr/share/ax/quantize_out.bin \
	frameworks/nn/lib/sv810/quantize_out.ezb:rootfs/usr/share/ax/quantize_out.ezb
