#
# lombo test driver specific Makefile
#

obj-y = common.o
obj-$(CONFIG_CLK_DRVIER_TEST)	+= clk-test.o
obj-$(CONFIG_PWM_DRVIER_TEST)	+= pwm-test.o
obj-$(CONFIG_VC_DRVIER_TEST)	+= vc-test.o
obj-$(CONFIG_MEMCTRL_DRVIER_TEST)	+= memctrl-test.o
obj-$(CONFIG_DMA_DRVIER_TEST)	+= dma-test.o
obj-$(CONFIG_LOMBO_DISP_TOOL)	+= lombo_disp_tool.o
obj-$(CONFIG_LOMBO_UVC_TOOL)   += lombo_uvc_tool.o
obj-$(CONFIG_VIRTUAL_TP)	+= virtual_tp.o
obj-$(CONFIG_GPIO_ALARM)	+= gpio_alarm.o