/* gtimer_set_cfg.h */

#ifndef ___GTIMER__SET_CFG__H___
#define ___GTIMER__SET_CFG__H___

/*
 * #define DEF_SET_GTIMER_GTMR_VER
 * #define DEF_SET_GTIMER_GTMR_VER_VER_L
 * #define DEF_SET_GTIMER_GTMR_VER_VER_H
 * #define DEF_SET_GTIMER_GTMR_VER_COMP
 * #define DEF_SET_GTIMER_GTMR0_CLK_CTRL
 * #define DEF_SET_GTIMER_GTMR0_CLK_CTRL_CLK_DIV
 * #define DEF_SET_GTIMER_GTMR0_CLK_CTRL_CLK_SEL
 * #define DEF_SET_GTIMER_GTMR0_STORE_VAL
 * #define DEF_SET_GTIMER_GTMR0_STORE_VAL_STORE_VAL
 * #define DEF_SET_GTIMER_GTMR0_CUR_VAL
 * #define DEF_SET_GTIMER_GTMR0_CUR_VAL_CUR_VAL
 * #define DEF_SET_GTIMER_GTMR0_CTRL
 * #define DEF_SET_GTIMER_GTMR0_CTRL_ENABLE
 * #define DEF_SET_GTIMER_GTMR0_CTRL_MODE
 * #define DEF_SET_GTIMER_GTMR0_CTRL_DIRECTION
 * #define DEF_SET_GTIMER_GTMR0_CTRL_NRDY
 * #define DEF_SET_GTIMER_GTMR0_INT_EN
 * #define DEF_SET_GTIMER_GTMR0_INT_EN_ENABLE
 * #define DEF_SET_GTIMER_GTMR0_CLR_INT_PENDING
 * #define DEF_SET_GTIMER_GTMR0_CLR_INT_PENDING_CLR
 * #define DEF_SET_GTIMER_GTMR0_INT_PENDING
 * #define DEF_SET_GTIMER_GTMR0_INT_PENDING_PENDING
 * #define DEF_SET_GTIMER_GTMR1_CLK_CTRL
 * #define DEF_SET_GTIMER_GTMR1_CLK_CTRL_CLK_DIV
 * #define DEF_SET_GTIMER_GTMR1_CLK_CTRL_CLK_SEL
 * #define DEF_SET_GTIMER_GTMR1_STORE_VAL
 * #define DEF_SET_GTIMER_GTMR1_STORE_VAL_STORE_VAL
 * #define DEF_SET_GTIMER_GTMR1_CUR_VAL
 * #define DEF_SET_GTIMER_GTMR1_CUR_VAL_CUR_VAL
 * #define DEF_SET_GTIMER_GTMR1_CTRL
 * #define DEF_SET_GTIMER_GTMR1_CTRL_ENABLE
 * #define DEF_SET_GTIMER_GTMR1_CTRL_MODE
 * #define DEF_SET_GTIMER_GTMR1_CTRL_DIRECTION
 * #define DEF_SET_GTIMER_GTMR1_CTRL_NRDY
 * #define DEF_SET_GTIMER_GTMR1_INT_EN
 * #define DEF_SET_GTIMER_GTMR1_INT_EN_ENABLE
 * #define DEF_SET_GTIMER_GTMR1_CLR_INT_PENDING
 * #define DEF_SET_GTIMER_GTMR1_CLR_INT_PENDING_CLR
 * #define DEF_SET_GTIMER_GTMR1_INT_PENDING
 * #define DEF_SET_GTIMER_GTMR1_INT_PENDING_PENDING
 * #define DEF_SET_GTIMER_GTMR2_CLK_CTRL
 * #define DEF_SET_GTIMER_GTMR2_CLK_CTRL_CLK_DIV
 * #define DEF_SET_GTIMER_GTMR2_CLK_CTRL_CLK_SEL
 * #define DEF_SET_GTIMER_GTMR2_STORE_VAL
 * #define DEF_SET_GTIMER_GTMR2_STORE_VAL_STORE_VAL
 * #define DEF_SET_GTIMER_GTMR2_CUR_VAL
 * #define DEF_SET_GTIMER_GTMR2_CUR_VAL_CUR_VAL
 * #define DEF_SET_GTIMER_GTMR2_CTRL
 * #define DEF_SET_GTIMER_GTMR2_CTRL_ENABLE
 * #define DEF_SET_GTIMER_GTMR2_CTRL_MODE
 * #define DEF_SET_GTIMER_GTMR2_CTRL_DIRECTION
 * #define DEF_SET_GTIMER_GTMR2_CTRL_NRDY
 * #define DEF_SET_GTIMER_GTMR2_INT_EN
 * #define DEF_SET_GTIMER_GTMR2_INT_EN_ENABLE
 * #define DEF_SET_GTIMER_GTMR2_CLR_INT_PENDING
 * #define DEF_SET_GTIMER_GTMR2_CLR_INT_PENDING_CLR
 * #define DEF_SET_GTIMER_GTMR2_INT_PENDING
 * #define DEF_SET_GTIMER_GTMR2_INT_PENDING_PENDING
 * #define DEF_SET_GTIMER_GTMR3_CLK_CTRL
 * #define DEF_SET_GTIMER_GTMR3_CLK_CTRL_CLK_DIV
 * #define DEF_SET_GTIMER_GTMR3_CLK_CTRL_CLK_SEL
 * #define DEF_SET_GTIMER_GTMR3_STORE_VAL
 * #define DEF_SET_GTIMER_GTMR3_STORE_VAL_STORE_VAL
 * #define DEF_SET_GTIMER_GTMR3_CUR_VAL
 * #define DEF_SET_GTIMER_GTMR3_CUR_VAL_CUR_VAL
 * #define DEF_SET_GTIMER_GTMR3_CTRL
 * #define DEF_SET_GTIMER_GTMR3_CTRL_ENABLE
 * #define DEF_SET_GTIMER_GTMR3_CTRL_MODE
 * #define DEF_SET_GTIMER_GTMR3_CTRL_DIRECTION
 * #define DEF_SET_GTIMER_GTMR3_CTRL_NRDY
 * #define DEF_SET_GTIMER_GTMR3_INT_EN
 * #define DEF_SET_GTIMER_GTMR3_INT_EN_ENABLE
 * #define DEF_SET_GTIMER_GTMR3_CLR_INT_PENDING
 * #define DEF_SET_GTIMER_GTMR3_CLR_INT_PENDING_CLR
 * #define DEF_SET_GTIMER_GTMR3_INT_PENDING
 * #define DEF_SET_GTIMER_GTMR3_INT_PENDING_PENDING
*/

#endif /* ___GTIMER__SET_CFG__H___ */
