obj-$(CONFIG_MEMCTRL)		+= memctrl/
obj-$(CONFIG_WIRELESS_PM)		+= wireless_pm/
obj-$(CONFIG_LOMBO_MISC)		+= lombo_misc/
obj-$(CONFIG_WIEGAND_RX)		+= wiegand_rx/
obj-$(CONFIG_WIEGAND_TX)		+= wiegand_tx/
obj-$(CONFIG_RFKILL_BT)		+= rfkill_bt/
obj-$(CONFIG_LOMBO_MOBILE_PM)		+= mobile_pm/
