/* wdog_get_cfg.h */

#ifndef ___WDOG__GET_CFG__H___
#define ___WDOG__GET_CFG__H___

/*
 * #define DEF_GET_WDOG_WDOG_VER_VER_L
 * #define DEF_GET_WDOG_WDOG_VER_VER_H
 * #define DEF_GET_WDOG_WDOG_VER_COMP
 * #define DEF_GET_WDOG_WDOG_CLK_CTRL_SEL
 * #define DEF_GET_WDOG_WDOG_CTRL_EN
 * #define DEF_GET_WDOG_WDOG_CTRL_RMOD
 * #define DEF_GET_WDOG_WDOG_CTRL_RPL
 * #define DEF_GET_WDOG_WDOG_CTRL_SU
 * #define DEF_GET_WDOG_WDOG_TMRPERIOD_TMRPERIOD
 * #define DEF_GET_WDOG_WDOG_CNT_CUR_VAL_CNT_CUR_VAL
 * #define DEF_GET_WDOG_WDOG_RESTART_RESTART
 * #define DEF_GET_WDOG_WDOG_INT_EN_ENABLE
 * #define DEF_GET_WDOG_WDOG_CLR_INT_PENDING_CLR
 * #define DEF_GET_WDOG_WDOG_INT_PENDING_PENDING
*/

#endif /* ___WDOG__GET_CFG__H___ */
