#ifndef __SUB_COMMON_H__
#define __SUB_COMMON_H__

typedef enum SUB_EFFECT_TYPE {
	SUB_EFFECT_TYPE_NONE = 0,
	SUB_EFFECT_TYPE_SCROLL_UP,
	SUB_EFFECT_TYPE_SCROLL_DOWN,
	SUB_EFFECT_TYPE_BANNER_LTOR, /* move from left to right */
	SUB_EFFECT_TYPE_BANNER_RTOL, /* move from right to left */
/*	SUB_EFFECT_TYPE_KARAOKE, */
} av_sub_effect_type_e;

typedef enum SUB_ALIGNMENT {
	SUB_ALIGNMENT_NONE = 0,
	SUB_ALIGNMENT_BOT_LEFT,
	SUB_ALIGNMENT_BOT_CENTER,
	SUB_ALIGNMENT_BOT_RIGHT,
	SUB_ALIGNMENT_MID_LEFT,
	SUB_ALIGNMENT_MID_CENTER,
	SUB_ALIGNMENT_MID_RIGHT,
	SUB_ALIGNMENT_TOP_LEFT,
	SUB_ALIGNMENT_TOP_CENTER,
	SUB_ALIGNMENT_TOP_RIGHT,
} av_sub_alignment_e;

typedef enum SUB_ENCODINGTYPE {
	SUB_ENCODE_TYPE_DEFAULT = 0,
	SUB_ENCODE_TYPE_ANSI,	/* ENGLISH ANSI 0*/
	SUB_ENCODE_TYPE_BITMAP,
	SUB_ENCODE_TYPE_GB2312, /* Simplified Chinese 134*/
	SUB_ENCODE_TYPE_BIG5, /* Traditional Chinese 136*/
	SUB_ENCODE_TYPE_GBK, /* Chinese character */
	SUB_ENCODE_TYPE_UTF8,
	SUB_ENCODE_TYPE_UTF16,
	SUB_ENCODE_TYPE_UTF32,
	SUB_ENCODE_TYPE_UNICODE,
} av_sub_encode_type_e;

typedef enum SUB_FONT_STYLE {
	SUB_FONT_STYLE_DEFAULT = 0,
	SUB_FONT_STYLE_ARIAL,
	SUB_FONT_STYLE_GBK_20,
	SUB_FONT_STYLE_MIC_YAHEI,
} av_sub_font_style_e;


typedef enum SUB_FONT_EFFECT_BOLD {
	SUB_FONT_BOLD_OFF = 0,
	SUB_FONT_BOLD_ON,
} font_bold_flag_e;

typedef enum SUB_FONT_EFFECT_ITALIC {
	SUB_FONT_ITALIC_OFF = 0,
	SUB_FONT_ITALIC_ON,
} font_italic_flag_e;

typedef enum SUB_FONT_EFFECT_UNDERLINE {
	SUB_FONT_UNDERLINE_OFF = 0,
	SUB_FONT_UNDERLINE_ON,
} font_underline_flag_e;

typedef enum SUB_FONT_EFFECT_STRIKEOUT {
	SUB_FONT_STRIKEOUT_OFF = 0,
	SUB_FONT_STRIKEOUT_ON,
} font_strikeout_flag_e;

typedef enum av_subtitle_type {
	SUB_NONE,
	SUB_TEXT,
	SUB_BITMAP,
} av_subtitle_type_e;

typedef enum charset_encode_type {
	IS_CHARSET_ENCODE_DEFAULT = -1,
	IS_CHARSET_ENCODE_UTF_8 = 0,
	IS_CHARSET_ENCODE_GBK = 1,
	IS_CHARSET_ENCODE_ASCII,
	IS_CHARSET_ENCODE_GBK2312,
	IS_CHARSET_ENCODE_UNICODE,
	IS_CHARSET_ENCODE_BIG_5,
	IS_CHARSET_ENCODE_GB18030,
} charset_encode_e;

#endif /* __ASS_COMMON_H__ */
