MEDIA_ROOT = $(call my-dir)
MEDIA_ROOT := $(MEDIA_ROOT)/..
MEDIA_CFLAGS := -D__linux__
#MEDIA_STRIP_MODULE := false
MEDIA_CFLAGS += -DCONFIG_MTEST

ifeq ($(TARGET_CHIP), n9v1)
	MEDIA_CFLAGS += -DCONFIG_ARCH_LOMBO_N9V1
endif
ifeq ($(TARGET_CHIP), n9v0)
	MEDIA_CFLAGS += -DCONFIG_ARCH_LOMBO_N9V0
endif
ifeq ($(TARGET_CHIP), n8v0)
	MEDIA_CFLAGS += -DCONFIG_ARCH_LOMBO_N8V0
endif
ifeq ($(TARGET_CHIP), n7v1)
	MEDIA_CFLAGS += -DCONFIG_ARCH_LOMBO_N7V1
endif
ifeq ($(MEDIA_DEBUG), 1)
	MEDIA_CFLAGS += -g3
endif

