LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE:=libssl
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_PREBUILT_LIBS   :=libssl.a
include $(BUILD_MULTI_PREBUILT)

LOCAL_MODULE:=libcrypto
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_PREBUILT_LIBS   :=libcrypto.a
include $(BUILD_MULTI_PREBUILT)



