Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd, str(Dir('#')),  os.path.join(cwd, "inc")]
group = DefineGroup('omx_core', src, depend = [""], CPPPATH = CPPPATH)

Return('group')
