obj-$(CONFIG_PINCTRL_N7)	+= pinctrl-lombo.o pinctrl-n7.o
obj-$(CONFIG_PINCTRL_N7_SIO)	+= pinctrl-lombo.o pinctrl-n7-sio.o
obj-$(CONFIG_PINCTRL_N9)	+= pinctrl-lombo.o pinctrl-n9.o
obj-$(CONFIG_PINCTRL_N9_SIO)	+= pinctrl-lombo.o pinctrl-n9-sio.o