#ifndef __AV_MEDIA_TYPE_H__
#define __AV_MEDIA_TYPE_H__

/* End of Stream */
#define AV_PACKET_FLAG_EOS		0x00000001

/* flag used to indicate is first packet after start or seek. */
#define AV_PACKET_FLAG_RESET		0x00000002

/**
 * Flag is used to discard packets which are required to maintain valid
 * decoder state but are not required for output and should be dropped
 * after decoding.
 **/
#define AV_PACKET_FLAG_DISCARD		0x00000004

/* The packet content is corrupted */
#define AV_PACKET_FLAG_CORRUPT		0x00000008

/**
 * End of Frame: The buffer contains exactly one end of frame and no data
 * occurs after the end of frame. This flag is an optional hint. The absence
 * of this flag does not imply the absence of an end of frame within the buffer.
 **/
#define AV_PACKET_FLAG_ENDOFFRAME	0x00000010

/* The packet contains a keyframe */
#define AV_PACKET_FLAG_KEY		0x00000020

/* Extra data present flag: there is extra data appended to the data stream
 * residing in the buffer
 */
#define AV_PACKET_FLAG_EXTRADATA	0x00000040

/* end of file */
#define AV_PACKET_FLAG_EOF		0x00000100

typedef enum av_media_type {
	AV_MEDIA_TYPE_INVALID = 0,
	AV_MEDIA_TYPE_VIDEO,
	AV_MEDIA_TYPE_AUDIO,
	AV_MEDIA_TYPE_SUBTITLE,
	AV_MEDIA_TYPE_DATA,
} av_media_type_e;

typedef enum av_muxer_type {
	AV_MUXER_TYPE_INVALID = 0,
	AV_MUXER_TYPE_AAC,
	AV_MUXER_TYPE_AMR,
	AV_MUXER_TYPE_APE,
	AV_MUXER_TYPE_AC3,
	AV_MUXER_TYPE_DTS,
	AV_MUXER_TYPE_FLAC,
	AV_MUXER_TYPE_G729,
	AV_MUXER_TYPE_OGG,
	AV_MUXER_TYPE_MP3,
	AV_MUXER_TYPE_WAV,

	AV_MUXER_TYPE_MP4 = 0X1000,
	AV_MUXER_TYPE_MOV,
	AV_MUXER_TYPE_MKV,
	AV_MUXER_TYPE_TS,
	AV_MUXER_TYPE_FLV,
	AV_MUXER_TYPE_AVI,
	AV_MUXER_TYPE_RAW,
	AV_MUXER_TYPE_ASF,
	AV_MUXER_TYPE_RM,
	AV_MUXER_TYPE_MPG,
} av_muxer_type_e;

typedef enum av_media_content {
	HAS_AUDIO = (1 << 0),
	HAS_VIDEO = (1 << 1),
	HAS_SUB   = (1 << 2)
} av_media_content_e;

typedef enum av_codec_type {
	AV_CODEC_TYPE_INVALID = 0,

	/* video codecs */
	AV_CODEC_TYPE_H264 = 1,
	AV_CODEC_TYPE_MJPEG,
	AV_CODEC_TYPE_MPEG2VIDEO, /* mpeg */
	AV_CODEC_TYPE_MPEG1VIDEO, /* mpeg */
	AV_CODEC_TYPE_MPEG4, /* mpeg4 */
	AV_CODEC_TYPE_FLV1, /* mpeg4 */
	AV_CODEC_TYPE_H263, /* mpeg4 */
	AV_CODEC_TYPE_MSMPEG4V3, /*mpeg4 */
	AV_CODEC_TYPE_RV30, /* rv34 */
	AV_CODEC_TYPE_RV40, /* rv34 */
	AV_CODEC_TYPE_WMV3, /* vc1 */
	AV_CODEC_TYPE_VC1, /* vc1 */
	AV_CODEC_TYPE_VP6F, /* vp6 */
	AV_CODEC_TYPE_HEVC,

	/* pcm codecs */
	AV_CODEC_TYPE_FIRST_AUDIO = 0x10000,
	AV_CODEC_TYPE_PCM_S8,
	AV_CODEC_TYPE_PCM_U8,
	AV_CODEC_TYPE_PCM_S16LE,
	AV_CODEC_TYPE_PCM_S16BE,
	AV_CODEC_TYPE_PCM_U16LE,
	AV_CODEC_TYPE_PCM_U16BE,
	AV_CODEC_TYPE_PCM_S24LE,
	AV_CODEC_TYPE_PCM_S24BE,
	AV_CODEC_TYPE_PCM_U24LE,
	AV_CODEC_TYPE_PCM_U24BE,
	AV_CODEC_TYPE_PCM_S32LE,
	AV_CODEC_TYPE_PCM_S32BE,
	AV_CODEC_TYPE_PCM_U32LE,
	AV_CODEC_TYPE_PCM_U32BE,
	AV_CODEC_TYPE_PCM_F32LE,
	AV_CODEC_TYPE_PCM_F64LE,
	AV_CODEC_TYPE_PCM_ALAW,
	AV_CODEC_TYPE_PCM_MULAW,
	AV_CODEC_TYPE_PCM_BLURAY,
	AV_CODEC_TYPE_PCM_DVD,

	AV_CODEC_TYPE_PCM_S64LE = 0x10800,
	AV_CODEC_TYPE_PCM_S64BE,

	/* various ADPCM codecs */
	AV_CODEC_TYPE_ADPCM_IMA_QT = 0x11000,
	AV_CODEC_TYPE_ADPCM_IMA_WAV,
	AV_CODEC_TYPE_ADPCM_IMA_DK3,
	AV_CODEC_TYPE_ADPCM_IMA_DK4,
	AV_CODEC_TYPE_ADPCM_IMA_WS,
	AV_CODEC_TYPE_ADPCM_MS,
	AV_CODEC_TYPE_ADPCM_G726,
	AV_CODEC_TYPE_ADPCM_CT,
	AV_CODEC_TYPE_ADPCM_SWF,
	AV_CODEC_TYPE_ADPCM_YAMAHA,
	AV_CODEC_TYPE_ADPCM_SBPRO_4,
	AV_CODEC_TYPE_ADPCM_SBPRO_3,
	AV_CODEC_TYPE_ADPCM_SBPRO_2,
	AV_CODEC_TYPE_G723_1,

	/* AMR */
	AV_CODEC_TYPE_AMR_NB = 0x12000,
	AV_CODEC_TYPE_AMR_WB,

	/* RealAudio codecs*/
	AV_CODEC_TYPE_RA_144 = 0x13000,
	AV_CODEC_TYPE_RA_288,

	/* audio codecs */
	AV_CODEC_TYPE_AAC = 0x15000,
	AV_CODEC_TYPE_AAC_LATM,
	AV_CODEC_TYPE_ALAC,
	AV_CODEC_TYPE_APE,
	AV_CODEC_TYPE_FLAC,
	AV_CODEC_TYPE_G729,
	AV_CODEC_TYPE_MP1,
	AV_CODEC_TYPE_MP2,
	AV_CODEC_TYPE_MP3,
	AV_CODEC_TYPE_MP3ADU,
	AV_CODEC_TYPE_MP3ON4,
	AV_CODEC_TYPE_OPUS,
	AV_CODEC_TYPE_QCELP,
	AV_CODEC_TYPE_VORBIS,
	AV_CODEC_TYPE_WAVPACK,
	AV_CODEC_TYPE_WMAV1,
	AV_CODEC_TYPE_WMAV2,
	AV_CODEC_TYPE_WMAVOICE,
	AV_CODEC_TYPE_WMAPRO,
	AV_CODEC_TYPE_WMALOSSLESS,
	AV_CODEC_TYPE_ATRAC1,
	AV_CODEC_TYPE_ATRAC3,
	AV_CODEC_TYPE_ATRAC3P,
	AV_CODEC_TYPE_COOK,
	AV_CODEC_TYPE_SIPR,
	AV_CODEC_TYPE_AC3,
	AV_CODEC_TYPE_EAC3,
	AV_CODEC_TYPE_TRUEHD,
	AV_CODEC_TYPE_DTS,
	AV_CODEC_TYPE_DTSHD,

	/* subtitle codecs */
	AV_CODEC_TYPE_FIRST_SUBTITLE = 0x20000,
	AV_CODEC_TYPE_ASS,
	AV_CODEC_TYPE_SRT,
	AV_CODEC_TYPE_STL,
	AV_CODEC_TYPE_LRC,
	AV_CODEC_TYPE_TXT,
	AV_CODEC_TYPE_TTS,
	AV_CODEC_TYPE_SUB,
	AV_CODEC_TYPE_VSF,
	AV_CODEC_TYPE_SMI,
	AV_CODEC_TYPE_JSS,
	AV_CODEC_TYPE_ASC,
	AV_CODEC_TYPE_OVR,
	AV_CODEC_TYPE_TTXT, /* timed text subtitle*/
	AV_CODEC_TYPE_VOBSUB,
	AV_CODEC_TYPE_PGS,
	AV_CODEC_TYPE_DVD_SUBTITLE,
	AV_CODEC_TYPE_DVDXSUB,
	AV_CODEC_TYPE_DVDSUB,
	AV_CODEC_TYPE_MAX
} av_codec_type_e;

#endif /* __AV_MEDIA_TYPE_H__ */
