#!/bin/sh

[ -x /usr/bin/hostapd ] || exit 0
[ -f /data/wifi/hostapd.conf ] || exit 0

case "$1" in
	start)
		printf "Starting hostapd: "
		ifconfig wlan0 up
		ifconfig wlan0 192.168.2.1
		start-stop-daemon -S -b -x /usr/bin/hostapd -- /data/wifi/hostapd.conf
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	stop)
		printf "Stopping hostapd: "
		ifconfig wlan0 down
		start-stop-daemon -K -q -x /usr/bin/hostapd
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	restart|reload)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit 0
