obj-$(CONFIG_ARCH_LOMBO) += lombo.o rtc_pm.o
obj-$(CONFIG_ARCH_LOMBO_N7V0) += csp-n7v0.o
obj-$(CONFIG_ARCH_LOMBO_N7V1) += csp-n7v1.o lib/
obj-$(CONFIG_SMP) += platsmp.o headsmp.o core_sync.o
obj-$(CONFIG_PM) += pm/
