LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := libmodem_at
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := \
	at_parser.c \
	config.c \
	ops.c
LOCAL_C_INCLUDES :=
#LOCAL_STRIP_MODULE := false
LOCAL_CFLAGS +=
LOCAL_CPPFLAGS :=
LOCAL_LDFLAGS :=
LOCAL_STATIC_LIBRARIES :=
LOCAL_SHARED_LIBRARIES := liblog
include $(BUILD_SHARED_LIBRARY)
