/* ptimer_get_cfg.h */

#ifndef ___PTIMER__GET_CFG__H___
#define ___PTIMER__GET_CFG__H___

/*
 * #define DEF_GET_PTIMER_PTMR_VER_VER_L
 * #define DEF_GET_PTIMER_PTMR_VER_VER_H
 * #define DEF_GET_PTIMER_PTMR_VER_COMP
 * #define DEF_GET_PTIMER_PTMR0_STORE_LOW_VAL_LOW
 * #define DEF_GET_PTIMER_PTMR0_STORE_HIGH_VAL_HIGH
 * #define DEF_GET_PTIMER_PTMR0_CUR_LOW_VAL_LOW
 * #define DEF_GET_PTIMER_PTMR0_CUR_HIGH_VAL_HIGH
 * #define DEF_GET_PTIMER_PTMR0_CTRL_ENABLE
 * #define DEF_GET_PTIMER_PTMR0_CTRL_MODE
 * #define DEF_GET_PTIMER_PTMR0_CTRL_DIRECTION
 * #define DEF_GET_PTIMER_PTMR0_CTRL_DIV
 * #define DEF_GET_PTIMER_PTMR0_INT_EN_ENABLE
 * #define DEF_GET_PTIMER_PTMR0_CLR_INT_PENDING_CLR
 * #define DEF_GET_PTIMER_PTMR0_INT_PENDING_PENDING
 * #define DEF_GET_PTIMER_PTMR1_STORE_LOW_VAL_LOW
 * #define DEF_GET_PTIMER_PTMR1_STORE_HIGH_VAL_HIGH
 * #define DEF_GET_PTIMER_PTMR1_CUR_LOW_VAL_LOW
 * #define DEF_GET_PTIMER_PTMR1_CUR_HIGH_VAL_HIGH
 * #define DEF_GET_PTIMER_PTMR1_CTRL_ENABLE
 * #define DEF_GET_PTIMER_PTMR1_CTRL_MODE
 * #define DEF_GET_PTIMER_PTMR1_CTRL_DIRECTION
 * #define DEF_GET_PTIMER_PTMR1_CTRL_DIV
 * #define DEF_GET_PTIMER_PTMR1_INT_EN_ENABLE
 * #define DEF_GET_PTIMER_PTMR1_CLR_INT_PENDING_CLR
 * #define DEF_GET_PTIMER_PTMR1_INT_PENDING_PENDING
*/

#endif /* ___PTIMER__GET_CFG__H___ */
