/* gpadc_get_cfg.h */

#ifndef ___GPADC__GET_CFG__H___
#define ___GPADC__GET_CFG__H___

/*
 * #define DEF_GET_GPADC_VER_VER_L
 * #define DEF_GET_GPADC_VER_VER_H
 * #define DEF_GET_GPADC_VER_COMP
 * #define DEF_GET_GPADC_GPAEN_GEN
 * #define DEF_GET_GPADC_GPAEN_CEN
 * #define DEF_GET_GPADC_GPAC_AUXIN0E
 * #define DEF_GET_GPADC_GPAC_AUXIN1E
 * #define DEF_GET_GPADC_GPAC_SDAE
 * #define DEF_GET_GPADC_GPAC_SRC
 * #define DEF_GET_GPADC_GPAC_FSS
 * #define DEF_GET_GPADC_GPAC_CCE
 * #define DEF_GET_GPADC_GPAC_DIVE
 * #define DEF_GET_GPADC_GPAC_OPC
 * #define DEF_GET_GPADC_GPAIE_AUX0IE
 * #define DEF_GET_GPADC_GPAIE_AUX1IE
 * #define DEF_GET_GPADC_GPAIE_S0DIE
 * #define DEF_GET_GPADC_GPAIE_S0UIE
 * #define DEF_GET_GPADC_GPAIE_S1DIE
 * #define DEF_GET_GPADC_GPAIE_S1UIE
 * #define DEF_GET_GPADC_GPAIE_S2DIE
 * #define DEF_GET_GPADC_GPAIE_S2UIE
 * #define DEF_GET_GPADC_GPAIE_AIN0DATIE
 * #define DEF_GET_GPADC_GPAIE_AIN1DATIE
 * #define DEF_GET_GPADC_GPAIE_S0DATIE
 * #define DEF_GET_GPADC_GPAIE_S1DATIE
 * #define DEF_GET_GPADC_GPAIE_S2DATIE
 * #define DEF_GET_GPADC_GPAIS_AUX0IS
 * #define DEF_GET_GPADC_GPAIS_AUX1IS
 * #define DEF_GET_GPADC_GPAIS_S0DIS
 * #define DEF_GET_GPADC_GPAIS_S0UIS
 * #define DEF_GET_GPADC_GPAIS_S1DIS
 * #define DEF_GET_GPADC_GPAIS_S1UIS
 * #define DEF_GET_GPADC_GPAIS_S2DIS
 * #define DEF_GET_GPADC_GPAIS_S2UIS
 * #define DEF_GET_GPADC_GPAIS_AIN0DATIS
 * #define DEF_GET_GPADC_GPAIS_AIN1DATIS
 * #define DEF_GET_GPADC_GPAIS_S0DATIS
 * #define DEF_GET_GPADC_GPAIS_S1DATIS
 * #define DEF_GET_GPADC_GPAIS_S2DATIS
 * #define DEF_GET_GPADC_GPAIC_AUXIN0PC
 * #define DEF_GET_GPADC_GPAIC_AUXIN1PC
 * #define DEF_GET_GPADC_GPAIC_S0DPC
 * #define DEF_GET_GPADC_GPAIC_S0UPC
 * #define DEF_GET_GPADC_GPAIC_S1DPC
 * #define DEF_GET_GPADC_GPAIC_S1UPC
 * #define DEF_GET_GPADC_GPAIC_S2DPC
 * #define DEF_GET_GPADC_GPAIC_S2UPC
 * #define DEF_GET_GPADC_GPAIC_AIN0DATPC
 * #define DEF_GET_GPADC_GPAIC_AIN1DATPC
 * #define DEF_GET_GPADC_GPAIC_S0DATPC
 * #define DEF_GET_GPADC_GPAIC_S1DATPC
 * #define DEF_GET_GPADC_GPAIC_S2DATPC
 * #define DEF_GET_GPADC_CDAT_DAT
 * #define DEF_GET_GPADC_AIN0DAT_DAT
 * #define DEF_GET_GPADC_AUX0HDAT_AUXIN0SHDAT
 * #define DEF_GET_GPADC_AUX0TDAT_AUXIN0TDAT
 * #define DEF_GET_GPADC_AIN1DAT_DAT
 * #define DEF_GET_GPADC_AUX1HDAT_AUXIN1HDAT
 * #define DEF_GET_GPADC_AUX1TDAT_AUXIN1TDAT
 * #define DEF_GET_GPADC_GSC_SEN
 * #define DEF_GET_GPADC_GSC_SSDAEN
 * #define DEF_GET_GPADC_GSC_SSR
 * #define DEF_GET_GPADC_S0CDAT_S0CDAT
 * #define DEF_GET_GPADC_S1CDAT_S1CDAT
 * #define DEF_GET_GPADC_S2CDAT_S2CDAT
 * #define DEF_GET_GPADC_S0DAT_S0ADCDAT
 * #define DEF_GET_GPADC_S0UTDAT_S0DATUT
 * #define DEF_GET_GPADC_S0DTDAT_S0DATDT
 * #define DEF_GET_GPADC_S1DAT_S1ADCDAT
 * #define DEF_GET_GPADC_S1UTDAT_S1DATUT
 * #define DEF_GET_GPADC_S1DTDAT_S1DATDT
 * #define DEF_GET_GPADC_S2DAT_S2ADCDAT
 * #define DEF_GET_GPADC_S2UTDAT_S2DATUT
 * #define DEF_GET_GPADC_S2DTDAT_S2DATDT
*/

#endif /* ___GPADC__GET_CFG__H___ */
