/* gicc_get_cfg.h */

#ifndef ___GICC__GET_CFG__H___
#define ___GICC__GET_CFG__H___

/*
 * #define DEF_GET_GICC_CTLR_ENABLEGRP0
 * #define DEF_GET_GICC_CTLR_ENABLEGRP1
 * #define DEF_GET_GICC_CTLR_ACKCTL
 * #define DEF_GET_GICC_CTLR_FIQEN
 * #define DEF_GET_GICC_CTLR_CBPR
 * #define DEF_GET_GICC_CTLR_FIQBYPDISGRP0
 * #define DEF_GET_GICC_CTLR_IRQBYPDISGRP0
 * #define DEF_GET_GICC_CTLR_FIQBYPDISGRP1
 * #define DEF_GET_GICC_CTLR_IRQBYPDISGRP1
 * #define DEF_GET_GICC_CTLR_EOIMODES
 * #define DEF_GET_GICC_CTLR_EOIMODENS
 * #define DEF_GET_GICC_PMR_PRIORITY
 * #define DEF_GET_GICC_BPR_BINARYPOINT
 * #define DEF_GET_GICC_IAR_INTERRUPTID
 * #define DEF_GET_GICC_IAR_CPUID
 * #define DEF_GET_GICC_EOIR_EOIINTID
 * #define DEF_GET_GICC_EOIR_CPUID
 * #define DEF_GET_GICC_RPR_PRIORITY
 * #define DEF_GET_GICC_HPPIR_PENDINTID
 * #define DEF_GET_GICC_HPPIR_CPUID
 * #define DEF_GET_GICC_ABPR_BINARYPOINT
 * #define DEF_GET_GICC_AIAR_INTERRUPTID
 * #define DEF_GET_GICC_AIAR_CPUID
 * #define DEF_GET_GICC_AEOIR_EOIINTID
 * #define DEF_GET_GICC_AEOIR_CPUID
 * #define DEF_GET_GICC_AHPPIR_PENDINTID
 * #define DEF_GET_GICC_AHPPIR_CPUID
 * #define DEF_GET_GICC_DIR_PENDINTID
 * #define DEF_GET_GICC_DIR_CPUID
*/

#endif /* ___GICC__GET_CFG__H___ */
