/* gicc_set_cfg.h */

#ifndef ___GICC__SET_CFG__H___
#define ___GICC__SET_CFG__H___

/*
 * #define DEF_SET_GICC_CTLR
 * #define DEF_SET_GICC_CTLR_ENABLEGRP0
 * #define DEF_SET_GICC_CTLR_ENABLEGRP1
 * #define DEF_SET_GICC_CTLR_ACKCTL
 * #define DEF_SET_GICC_CTLR_FIQEN
 * #define DEF_SET_GICC_CTLR_CBPR
 * #define DEF_SET_GICC_CTLR_FIQBYPDISGRP0
 * #define DEF_SET_GICC_CTLR_IRQBYPDISGRP0
 * #define DEF_SET_GICC_CTLR_FIQBYPDISGRP1
 * #define DEF_SET_GICC_CTLR_IRQBYPDISGRP1
 * #define DEF_SET_GICC_CTLR_EOIMODES
 * #define DEF_SET_GICC_CTLR_EOIMODENS
 * #define DEF_SET_GICC_PMR
 * #define DEF_SET_GICC_PMR_PRIORITY
 * #define DEF_SET_GICC_BPR
 * #define DEF_SET_GICC_BPR_BINARYPOINT
 * #define DEF_SET_GICC_IAR
 * #define DEF_SET_GICC_IAR_INTERRUPTID
 * #define DEF_SET_GICC_IAR_CPUID
 * #define DEF_SET_GICC_EOIR
 * #define DEF_SET_GICC_EOIR_EOIINTID
 * #define DEF_SET_GICC_EOIR_CPUID
 * #define DEF_SET_GICC_RPR
 * #define DEF_SET_GICC_RPR_PRIORITY
 * #define DEF_SET_GICC_HPPIR
 * #define DEF_SET_GICC_HPPIR_PENDINTID
 * #define DEF_SET_GICC_HPPIR_CPUID
 * #define DEF_SET_GICC_ABPR
 * #define DEF_SET_GICC_ABPR_BINARYPOINT
 * #define DEF_SET_GICC_AIAR
 * #define DEF_SET_GICC_AIAR_INTERRUPTID
 * #define DEF_SET_GICC_AIAR_CPUID
 * #define DEF_SET_GICC_AEOIR
 * #define DEF_SET_GICC_AEOIR_EOIINTID
 * #define DEF_SET_GICC_AEOIR_CPUID
 * #define DEF_SET_GICC_AHPPIR
 * #define DEF_SET_GICC_AHPPIR_PENDINTID
 * #define DEF_SET_GICC_AHPPIR_CPUID
 * #define DEF_SET_GICC_DIR
 * #define DEF_SET_GICC_DIR_PENDINTID
 * #define DEF_SET_GICC_DIR_CPUID
*/

#endif /* ___GICC__SET_CFG__H___ */
